---
new_page_extension: md
auto_deploy: false
admin_path: "/dist"
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: content/data/home.json
  label: Homepage
- type: directory
  path: content/articles
  label: Articles
  create: documents
  match: "**/*"
  templates:
  - article
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - page
- type: heading
  label: Extra
upload_dir: static/media
public_path: "/media"
front_matter_path: "/media"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
